def stock_names_symbols():
    stocks = [
        ("Adani Ports and Special Economic Zone Limited", "ADANIPORTS.csv"),
        ("Asian Paints Limited", "ASIANPAINT.csv"),
        ("Axis Bank Limited", "AXISBANK.csv"),
        ("Bajaj Auto Limited", "BAJAJ-AUTO.csv"),
        ("Bajaj Finserv Limited", "BAJAJFINSV.csv"),
        ("Bajaj Finance Limited", "BAJFINANCE.csv"),
        ("Bharti Airtel Limited", "BHARTIARTL.csv"),
        ("Bharat Petroleum Corporation Limited", "BPCL.csv"),
        ("Britannia Industries Limited", "BRITANNIA.csv"),
        ("Cipla Limited", "CIPLA.csv"),
        ("Coal India Limited", "COALINDIA.csv"),
        ("Dr. Reddy's Laboratories Limited", "DRREDDY.csv"),
        ("Eicher Motors Limited", "EICHERMOT.csv"),
        ("GAIL (India) Limited", "GAIL.csv"),
        ("Grasim Industries Limited", "GRASIM.csv"),
        ("HCL Technologies Limited", "HCLTECH.csv"),
        ("Housing Development Finance Corporation Limited", "HDFC.csv"),
        ("HDFC Bank Limited", "HDFCBANK.csv"),
        ("Hero MotoCorp Limited", "HEROMOTOCO.csv"),
        ("Hindalco Industries Limited", "HINDALCO.csv"),
        ("Hindustan Unilever Limited", "HINDUNILVR.csv"),
        ("ICICI Bank Limited", "ICICIBANK.csv"),
        ("IndusInd Bank Limited", "INDUSINDBK.csv"),
        ("Bharti Infratel Limited", "INFRATEL.csv"),
        ("Infosys Limited", "INFY.csv"),
        ("Indian Oil Corporation Limited", "IOC.csv"),
        ("ITC Limited", "ITC.csv"),
        ("JSW Steel Limited", "JSWSTEEL.csv"),
        ("Kotak Mahindra Bank Limited", "KOTAKBANK.csv"),
        ("Larsen & Toubro Limited", "LT.csv"),
        ("Maruti Suzuki India Limited", "MARUTI.csv"),
        ("Mahindra & Mahindra Limited", "MM.csv"),
        ("Nestle India Limited", "NESTLEIND.csv"),
        ("Nifty 50", "NIFTY50_all.csv"),
        ("NTPC Limited", "NTPC.csv"),
        ("Oil and Natural Gas Corporation Limited", "ONGC.csv"),
        ("Power Grid Corporation of India Limited", "POWERGRID.csv"),
        ("Reliance Industries Limited", "RELIANCE.csv"),
        ("State Bank of India", "SBIN.csv"),
        ("Shree Cement Limited", "SHREECEM.csv"),
        ("Sun Pharmaceutical Industries Limited", "SUNPHARMA.csv"),
        ("Tata Motors Limited", "TATAMOTORS.csv"),
        ("Tata Steel Limited", "TATASTEEL.csv"),
        ("Tata Consultancy Services Limited", "TCS.csv"),
        ("Tech Mahindra Limited", "TECHM.csv"),
        ("Titan Company Limited", "TITAN.csv"),
        ("UltraTech Cement Limited", "ULTRACEMCO.csv"),
        ("UPL Limited", "UPL.csv"),
        ("Vedanta Limited", "VEDL.csv"),
        ("Wipro Limited", "WIPRO.csv"),
        ("Zee Entertainment Enterprises Limited", "ZEEL.csv"),
    ]
    return stocks
